### ISSUE TITLE
Create integration of the Ephemery testnet for Dappnode

### ISSUE THREAD

**Issue by chuygarcia92** [taxmeifyoucan/ephemeral-testnet#6]
This is the PR with changes to the Dappmanager. Packages for the Stakers menu will follow so testing can begin.

https://github.com/dappnode/DNP_DAPPMANAGER/pull/2048

![image](https://github.com/user-attachments/assets/b5fd0d17-a18e-4143-96e5-39bdea531192)

**Comment by taxmeifyoucan** [comment]
This is awesome, thanks a lot Chuy! I am gonna give it a try in vm with dappnode.

But this repo is actually not used anymore, we moved it to Ephemery org - please post relevant info here or open PR to add it https://github.com/ephemery-testnet/ephemery-resources/
